# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PC\Desktop\BipedUI.ui'
#
# Created: Thu Apr 28 12:19:11 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_BipedUI(object):
    def setupUi(self, BipedUI):
        BipedUI.setObjectName("BipedUI")
        BipedUI.resize(219, 372)
        self.tabWidget = QtWidgets.QTabWidget(BipedUI)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 221, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.Biped = QtWidgets.QWidget()
        self.Biped.setObjectName("Biped")
        self.widget = QtWidgets.QWidget(self.Biped)
        self.widget.setGeometry(QtCore.QRect(0, 0, 241, 211))
        self.widget.setObjectName("widget")
        self.TransJointButton = QtWidgets.QPushButton(self.widget)
        self.TransJointButton.setGeometry(QtCore.QRect(20, 80, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.TransJointButton.setFont(font)
        self.TransJointButton.setObjectName("TransJointButton")
        self.ConvertButton = QtWidgets.QPushButton(self.widget)
        self.ConvertButton.setGeometry(QtCore.QRect(20, 140, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.ConvertButton.setFont(font)
        self.ConvertButton.setObjectName("ConvertButton")
        self.GuideButton = QtWidgets.QPushButton(self.widget)
        self.GuideButton.setGeometry(QtCore.QRect(20, 20, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.GuideButton.setFont(font)
        self.GuideButton.setObjectName("GuideButton")
        self.tabWidget.addTab(self.Biped, "")
        self.Facial = QtWidgets.QWidget()
        self.Facial.setObjectName("Facial")
        self.widget_2 = QtWidgets.QWidget(self.Facial)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 231, 351))
        self.widget_2.setObjectName("widget_2")
        self.OtherSetButton = QtWidgets.QPushButton(self.widget_2)
        self.OtherSetButton.setGeometry(QtCore.QRect(20, 200, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.OtherSetButton.setFont(font)
        self.OtherSetButton.setObjectName("OtherSetButton")
        self.BlendConnectButton = QtWidgets.QPushButton(self.widget_2)
        self.BlendConnectButton.setGeometry(QtCore.QRect(20, 260, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.BlendConnectButton.setFont(font)
        self.BlendConnectButton.setObjectName("BlendConnectButton")
        self.EyeSetButton = QtWidgets.QPushButton(self.widget_2)
        self.EyeSetButton.setGeometry(QtCore.QRect(20, 20, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.EyeSetButton.setFont(font)
        self.EyeSetButton.setObjectName("EyeSetButton")
        self.TransEyeJointButton = QtWidgets.QPushButton(self.widget_2)
        self.TransEyeJointButton.setGeometry(QtCore.QRect(20, 80, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.TransEyeJointButton.setFont(font)
        self.TransEyeJointButton.setObjectName("TransEyeJointButton")
        self.LipSetButton = QtWidgets.QPushButton(self.widget_2)
        self.LipSetButton.setGeometry(QtCore.QRect(20, 140, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.LipSetButton.setFont(font)
        self.LipSetButton.setObjectName("LipSetButton")
        self.tabWidget.addTab(self.Facial, "")
        self.MadeByMiffyText = QtWidgets.QLabel(BipedUI)
        self.MadeByMiffyText.setGeometry(QtCore.QRect(10, 350, 81, 16))
        self.MadeByMiffyText.setObjectName("MadeByMiffyText")

        self.retranslateUi(BipedUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BipedUI)

    def retranslateUi(self, BipedUI):
        BipedUI.setWindowTitle(QtWidgets.QApplication.translate("BipedUI", "BipedUI", None, -1))
        self.TransJointButton.setText(QtWidgets.QApplication.translate("BipedUI", "Trans Joint", None, -1))
        self.ConvertButton.setText(QtWidgets.QApplication.translate("BipedUI", "Convert", None, -1))
        self.GuideButton.setText(QtWidgets.QApplication.translate("BipedUI", "Guide", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Biped), QtWidgets.QApplication.translate("BipedUI", "Biped", None, -1))
        self.OtherSetButton.setText(QtWidgets.QApplication.translate("BipedUI", "Other Set", None, -1))
        self.BlendConnectButton.setText(QtWidgets.QApplication.translate("BipedUI", "Blend Connect", None, -1))
        self.EyeSetButton.setText(QtWidgets.QApplication.translate("BipedUI", "Eye Set", None, -1))
        self.TransEyeJointButton.setText(QtWidgets.QApplication.translate("BipedUI", "Trans Eye Joint", None, -1))
        self.LipSetButton.setText(QtWidgets.QApplication.translate("BipedUI", "Lip Set", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Facial), QtWidgets.QApplication.translate("BipedUI", "Facial", None, -1))
        self.MadeByMiffyText.setText(QtWidgets.QApplication.translate("BipedUI", "made by Miffy", None, -1))